### ISSUE TITLE
Error on email sign in: FirebaseError: Firebase: Error (auth/operation-not-allowed).

### ISSUE THREAD

**Issue by Johnrobmiller** [XaFaK-01/Next.js-Private-Routes-Firebase-Modular-SDK-9-authentication-Email-Google-Github-Face#1]
I cloned the repo, followed your setup instructions, but when I tried to login via email, I got the following error:

FirebaseError: Firebase: Error (auth/operation-not-allowed).

**Comment by XaFaK-01** [comment]
You most probably haven't enabled  "Email/Password" in your firebase console.
You can do so by navigating to:
console.firebase.google.com --> Select your project --> Authentication --> Sign in method tab --> Add new provider --> 
Enable Email/Password

**Comment by XaFaK-01** [comment]
> I cloned the repo, followed your setup instructions, but when I tried to login via email, I got the following error:
> 
> FirebaseError: Firebase: Error (auth/operation-not-allowed).

You most probably haven't enabled "Email/Password" in your firebase console.
You can do so by navigating to:
console.firebase.google.com --> Select your project --> Authentication --> Sign in method tab --> Add new provider -->
Enable Email/Password

**Comment by Johnrobmiller** [comment]
I figured it out, and you are very close.  It was because I accidentally copy/pasted the config from the wrong project.  😅. In the wrong project, I had email/password login disabled.

My apologies for wasting your time about this, and thanks for publishing this repo, it is extremely helpful.

**Comment by XaFaK-01** [comment]
> I figured it out, and you are very close.  It was because I accidentally copy/pasted the config from the wrong project.  😅. In the wrong project, I had email/password login disabled.
> 
> My apologies for wasting your time about this, and thanks for publishing this repo, it is extremely helpful.

Glad that I could be of help!
